version: "3.7"

services:
    app:
        build: .
        container_name: app
        volumes:
            - .:/var/www
        # entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/docker-entrypoint.sh
        networks:
            - app-network
        depends_on:
            - db
            - redis
        # environment:
        #     DB_HOST: "db"
        #     DB_DATABASE: "laravel"
        #     DB_USERNAME: "root"
        #     DB_PASSWORD: "root"

    nginx:
        build: ./.docker/nginx
        container_name: nginx
        entrypoint: dockerize -template /etc/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf -wait tcp://app:9000 -timeout 40s nginx -g "daemon off;"
        restart: always
        tty: true
        environment:
            NGINX_HOST: app
            NGINX_PORT: 9000
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    redis:
        image: redis:alpine
        container_name: redis
        expose:
            - 6379
        networks:
            - app-network

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: "laravel"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "root"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
